version: '3.7'
services:
  mysql_container:
    image: circleci/mysql
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
      - './docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/'

    security_opt:
      - seccomp:unconfined

    restart: always

    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cooler_car
      MYSQL_USER: car
      MYSQL_PASSWORD: root
      MYSQL_HOST: localhost

    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G

    networks:
      - redecita

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: '3'
    networks:
      - redecita

  webserver:
    image: custom-airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_HOST=postgres
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
    logging:
      options:
        max-size: 10m
        max-file: '3'
    volumes:
        - ./../../scripts/etls/dags:/usr/local/airflow/dags
        - ./../../data:/usr/local/airflow/dags/templates
        - ./../../scripts/etls/dags/templates:/usr/local/airflow/dags/templates/sql_scritps
        - ./../../scripts/etls/dags/operators:/usr/local/airflow/dags/operators
        - ./variables:/usr/local/airflow/variables
        - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg

    ports:
      - '8080:8080'
    command: webserver
    healthcheck:
      test: ['CMD-SHELL', '[ -f /usr/local/airflow/airflow-webserver.pid ]']
      interval: 30s
      timeout: 30s
      retries: 3

    networks:
        - redecita

networks:
  redecita:
    driver: bridge
