TRUNCATE TABLE DIM.AGG_RENTALS;
TRUNCATE TABLE DIM.DIM_BRANCH_OFFICE;
TRUNCATE TABLE DIM.DIM_CAR;
TRUNCATE TABLE DIM.DIM_PAYMENT_METHOD;
TRUNCATE TABLE DIM.DIM_PERSON;
TRUNCATE TABLE DIM.DIM_RENTAL;
TRUNCATE TABLE DIM.DIM_USER;