INSERT INTO DIM.DIM_BRANCH_OFFICE
SELECT BO.BRANCH_OFFICE_ID,
       BO.BRANCH_CODE BRANCH_OFFICE_CODE,
       HBO.NAME       BRANCH_OFFICE_NAME,
       HBO.ADDRESS_1  BRANCH_OFFICE_ADDRESS_1,
       HBO.ADDRESS_2  BRANCH_OFFICE_ADDRESS_2,
       HBO.CITY       BRANCH_OFFICE_ADDRESS_CITY,
       HBO.CP         BRANCH_OFFICE_CP,
       HBO.STATE      BRANCH_OFFICE_STATE
FROM CAT_BRANCH_OFFICE BO
INNER JOIN HIST_BRANCH_OFFICE HBO
ON BO.BRANCH_OFFICE_ID = HBO.BRANCH_OFFICE_ID AND HBO.IS_ACTIVE