INSERT INTO DIM.DIM_CAR
SELECT  C.CAR_ID,
        HC.HASH_KEY,
        LM.CODE MOTOR_CODE,
        LM.DESCRIPTION_ES MOTOR_DESCRIPTION_ES,
        LTMT.CODE TRADE_MARK_CODE,
        LTMT.DESCRIPTION_ES TRADE_MARK_DESCRIPTION_ES,
        LC.CODE CAR_TYPE_CODE,
        LC.DESCRIPTION_ES CAR_TYPE_DESCRIPTION_ES,
        HB.BRANCH_OFFICE_ID,
        HB.NAME BRANCH_OFFICE_NAME,
        CB.BRANCH_CODE BRANCH_OFFICE_CODE,
        HC.NIV,
        HC.YEAR,
        HC.EXPEDITION,
        HC.CAPACITY,
        HC.USER_ID,
        HC.MODEL CAR_MODEL
FROM CAT_CAR C
INNER JOIN HIST_CAR HC
ON HC.CAR_ID = C.CAR_ID AND HC.IS_ACTIVE
INNER JOIN LU_MOTOR_TYPE LM
ON LM.MOTOR_TYPE_ID = HC.MOTOR_TYPE_ID AND LM.IS_ACTIVE
INNER JOIN LU_TRADE_MARK_TYPE LTMT ON HC.TRADE_MARK_TYPE_ID = LTMT.TRADE_MARK_TYPE_ID AND LTMT.IS_ACTIVE
INNER JOIN LU_CAR_TYPE LC ON LC.CAR_TYPE_ID = HC.CAR_TYPE_ID AND LC.IS_ACTIVE
INNER JOIN CAT_BRANCH_OFFICE CB ON CB.BRANCH_OFFICE_ID = HC.BRANCH_OFFICE_ID
INNER JOIN HIST_BRANCH_OFFICE HB ON HB.BRANCH_OFFICE_ID = HC.BRANCH_OFFICE_ID AND HB.IS_ACTIVE
ORDER BY 1 ASC;
