
INSERT INTO DIM.DIM_PAYMENT_METHOD
SELECT RPM.WALLET_ID,
       RPM.USER_ID,
       PM.PAYMENT_METHOD_ID,
       PM.PAYMENT_METHOD_TYPE_ID,
       PMT.CODE PAYMENT_METHOD_TYPE_CODE,
       PMT.DESCRIPTION_ES PAYMENT_METHOD_TYPE_DESCRIPTION_ES,
       RCC.CREDIT_CARD_ID,
       CC.NUMBER CREDIT_CARD_NUMBER,
       CC.EXPIRY_DATE CREDIT_CARD_EXPIRY_DATE,
       RPA.PAYPAL_ACCOUNT_ID,
       PA.EMAIL PAYPAL_ACCOUNT_EMAIL,
       'XXXXXXXXXXXX' PAYPAL_ACCOUNT_EMAIL_PASSWORD
FROM CAT_PAYMENT_METHOD PM
INNER JOIN LU_PAYMENT_METHOD_TYPE PMT
ON PM.PAYMENT_METHOD_TYPE_ID = PMT.PAYMENT_METHOD_TYPE_ID AND PMT.IS_ACTIVE
INNER JOIN REL_PAYMENT_METHOD RPM ON PM.PAYMENT_METHOD_ID = RPM.PAYMENT_METHOD_ID AND RPM.IS_ACTIVE
LEFT JOIN CAT_PAYMENT_METHOD CPM ON PMT.PAYMENT_METHOD_TYPE_ID = CPM.PAYMENT_METHOD_TYPE_ID JOIN REL_CREDIT_CARD RCC ON PM.PAYMENT_METHOD_ID = RCC.PAYMENT_METHOD_ID AND RCC.IS_ACTIVE
LEFT JOIN CAT_CREDIT_CARD CC ON  RCC.CREDIT_CARD_ID = CC.CREDIT_CARD_ID
LEFT JOIN REL_PAYPAL_ACCOUNT RPA ON RPA.PAYMENT_METHOD_ID = PM.PAYMENT_METHOD_ID  AND RPA.IS_ACTIVE
LEFT JOIN CAT_PAYPAL_ACCOUNT PA ON  PA.PAYPAL_ACCOUNT_ID = RPA.PAYMENT_METHOD_ID
