
INSERT INTO DIM.DIM_PERSON
SELECT CP.PERSON_ID,
       HP.NAME,
       HP.SECOND_NAME,
       HP.LAST_NAME,
       HP.SECOND_LAST_NAME,
       HP.CURP,
       HP.RFC,
       HP.INE_NUMBER,
       PT.CODE PERSON_TYPE_CODE,
       PT.DESCRIPTION_ES PERSON_TYPE_DESCRIPTION_ES,
       HP.USER_ID
FROM CAT_PERSON CP
INNER JOIN HIST_PERSON HP ON CP.PERSON_ID = HP.PERSON_ID AND CP.PERSON_ID AND HP.IS_ACTIVE
INNER JOIN LU_PERSON_TYPE AS PT ON PT.PERSON_TYPE_ID = HP.PERSON_TYPE_ID AND PT.IS_ACTIVE

