

INSERT INTO DIM.DIM_RENTAL
SELECT CR.TRIP_ID,
       CR.NUMBER TRIP_NUMBER,
       RUR.USER_ID,
       RUR.RENTAL_DATE,
       RUR.DELIVERY_DATE,
       RUR.BRANCH_OFFICE_ID,
       CBO.BRANCH_CODE,
       RUR.PAYMENT_METHOD_ID,
       LMP.CODE LU_PAYMENT_METHOD_TYPE_CODE,
       LMP.DESCRIPTION_ES LU_PAYMENT_METHOD_TYPE_DESCRIPTION_ES,
       RUR.FARE,
       RUR.DAMAGE_FEE,
       RUR.CAR_ID,
       HC.NIV
       FROM CAT_RENT CR
INNER JOIN REL_USER_RENT RUR ON CR.TRIP_ID = RUR.TRIP_ID AND RUR.IS_ACTIVE
INNER JOIN CAT_BRANCH_OFFICE CBO ON RUR.BRANCH_OFFICE_ID = CBO.BRANCH_OFFICE_ID
INNER JOIN CAT_PAYMENT_METHOD CPM ON CPM.PAYMENT_METHOD_ID = RUR.PAYMENT_METHOD_ID
INNER JOIN LU_PAYMENT_METHOD_TYPE LMP ON LMP.PAYMENT_METHOD_TYPE_ID = CPM.PAYMENT_METHOD_TYPE_ID
INNER JOIN CAT_CAR CC ON CC.CAR_ID = RUR.CAR_ID
INNER JOIN  HIST_CAR HC ON HC.CAR_ID = CC.CAR_ID AND HC.IS_ACTIVE;