INSERT INTO DIM.DIM_USER
SELECT C.USER_ID,
       HC.PHONE,
       'XXXXX' as "PASSWORD",
       LUT.CODE USER_TYPE_CODE,
       LUT.DESCRIPTION_ES USER_TYPE_DESCRIPTION_ES

FROM CAT_USER C
INNER JOIN HIST_USER HC ON C.USER_ID = HC.USER_ID AND HC.IS_ACTIVE
INNER JOIN LU_USER_TYPE LUT ON HC.USER_TYPE_ID = LUT.USER_TYPE_ID AND LUT.IS_ACTIVE
ORDER BY 1 DESC;


